name: Demo Work Flow

on:
    push:
        branches: ['main']

    workflow_dispatch:
        inputs:

            enviorment:
                description: This is enviorment
                type: choice
                required: true    
                default: 'DEV'
                options:
                    - DEV
                    - PROD
                    - QA

            version:
                description: This is version
                type: string
                required: true    
                default: 'v-1.0.0'
        

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Complie Code
              run: echo "In this step we'll complie the code"

            - name: Docker Build
              run: echo "In this Step We'll do Docker Build"
              
    Test:
        needs: [Build]
        runs-on: ubuntu-latest
        steps:
            - name: Unit Test
              run: echo "In This step we will do unit test"          
            
            - name: Integration Test
              run: echo "In This step we will do Integration Test"          
              

    Deploy:
        needs: [Build, Test]
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'
        steps:
            - name: Deploy the code
              if: inputs.enviorment == 'DEV'
              run: echo "Deploying the code version ${{inputs.version}} on ${{inputs.enviorment}}"   
              
            - name: Deploy the code
              if: inputs.enviorment == 'PROD'
              run: echo "Deploying the code version ${{inputs.version}} on ${{inputs.enviorment}}"   
              
            - name: Deploy the code
              if: inputs.enviorment == 'QA'
              run: echo "Deploying the code version ${{inputs.version}} on ${{inputs.enviorment}}"     