name: Demo WorkFlow

on:
  push:
    branches: [main]
  workflow_dispatch: 

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: first step
        run: echo "Hello! Your first workflow is running"
      
      - name: show github context
        run: |
          echo "Respository: ${{ github.repository }}"  
          echo "Event: ${{ github.event_name }}"  
          echo "Actor: ${{ github.actor }}"
          
      - name: checkout the ubuntu location
        run: pwd    
      
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: List Files
        run: ls -la  