name: Quiz Workflow 2

on:
    workflow_dispatch:
        
jobs:
    job-alpha:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I am the first job"
    
    job-beta:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I am the second job"        
