name: Quiz Workflow 3

on: 
    workflow_dispatch:
        inputs:
            username:
                description: "Provide your username"
                default: "Student"
                type: string
                required: true

            
            difficulty:
                description: "Select the difficulty level"
                type: choice
                required: true
                options:
                    - easy
                    - medium
                    - hard

jobs:
    great:
        runs-on: ubuntu-latest
        steps:
            - run: | 
                echo "Hello ${{github.event.inputs.username}}"                    
                echo "You selected ${{github.event.inputs.difficulty}}"
                echo "${{github.action}}"
                echo "${{github.action_path}}"
                echo "${{github.action_ref}}"
                echo "${{github.action_repository}}"