name: step conditional actions

on:
    workflow_dispatch:

jobs:
    condtional-access:
        runs-on: ubuntu-latest
        steps: 
            - name: step1
              id: step1id  
              run: |
                echo "I'm step"          
                exit 1
              continue-on-error: true  

            - name: step2
              if: steps.step1id.outcome == 'success'
              run: echo "All previous steps has been passed"
              
            - name: step3
              if: steps.step1id.outcome == 'failure'
              run: echo "execute on failed step"
              
            - name: step4
              run: echo "awalys run"  
                    