name: This is Workflow for the Workflow dispathcher

on:
    workflow_dispatch:

jobs:
    workflowjob:
        runs-on: ubuntu:latest
        steps:
            - run: |
                echo "I am manual trigreed the workflow"        